### PR TITLE
Add onnx export size option

### PR DESCRIPTION
**Pull request by zhen8838**
1. add tsize choice in tools/export_onnx.py

<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>

### CODE REVIEW

**Comment by zhen8838** [comment]
I add [YOLOX k210 support](https://github.com/zhen8838/nncase/tree/yolox/examples/yolox), but k210 has not sufficient memory, so I add `tsize` option in onnx model export script.

**Comment by FateScript** [comment]
You could modify tsize by add string `test_size (a, b)`, sorry for not informing in docs.

**Comment by zhen8838** [comment]
ok thanks

**Comment by zhanggan123456** [comment]
Have you succeeded in visualization

**Pull request closed without merging**
