### PR TITLE
About the test video stream cause the  out of memroy

### PR DESCRIPTION
**Pull request by F0xZz**
in the fuction of  blobFromImage(pr_img) new the pointer to the float and don't delete this will cause the out of memroy

### CODE REVIEW

**Comment by developer0hye** [comment]
How about naming 'num_classes' instead of 'num_class'?

https://github.com/Megvii-BaseDetection/YOLOX/search?q=num_classes

**Comment by FateScript** [comment]
> How about naming 'num_classes' instead of 'num_class'?
> 
> https://github.com/Megvii-BaseDetection/YOLOX/search?q=num_classes

Good point, `num_classes` is better.

**Comment by FateScript** [comment]
Could you cherry-pick your commit? I believe that the only change is only two lines?

**Comment by F0xZz** [comment]
> Could you cherry-pick your commit? I believe that your modification is only two lines?

Firstly thanks the author support the demo ,and the function of float* blobFromImage(cv::Mat& img) ,you new a float* and will declare a store space to store if you only test one img this program shutdown and this storage space will be free.But when test on video each frame will go into this function to new a float*.
this is my test :
test on no delete :
1min
Screenshot from 2021-08-09 12-54-46
2min
Screenshot from 2021-08-09 12-55-23
test on has deleted the pointer
Screenshot from 2021-08-09 12-54-12

**Comment by FateScript** [comment]
Thx, could you help  changing `num_class` to `num_classes` and check again?

**Comment by FateScript** [comment]
I will edit it and merge. LGTM.

**Pull request merged**
