### PR TITLE
Change os.path to Pathlib to avoid issues with Windows.

### PR DESCRIPTION
**Pull request by robin-maillot**
I noticed some issue with Windows due to the hardcoding of "/" in certain places. One example is when running: `python .\tools\demo.py video -n yolox-s -c ..\yolox_s.pth --path path\to\video\video_name  --conf 0.25  --nms 0.45 --tsize 640 - save_result --device gpu` the video containing the results overwrote my initial video and caused issues.

This was due to:
https://github.com/Megvii-BaseDetection/YOLOX/blob/25f116b3145db3f2808ffbe722677d301e34f40d/tools/demo.py#L219

There were a couple other places with hardcoded seperators so I changed to using pathlib to easily access the different parts of a path (using `parents` `stem` and `suffix` functions).

I think this makes the repo a little cleaner. Everything runs well on windows now.

Let me know what you think :)

### CODE REVIEW

**Comment by FateScript** [comment]
A simple way to avoid this is using ```os.sep``` and some of our method is used for string, not pathlib.

**Comment by FateScript** [comment]
Thanks for contribtion, please sign CLA .

**Comment by robin-maillot** [comment]
> Thanks for contribtion, please sign CLA .

@FateScript I have accepted it normally (see screenshot below)

image


> A simple way to avoid this is using `os.sep` and some of our method is used for string, not pathlib.

Yep definetly I just figured pathlib is becoming more and more a standard and it makes code more readable in my opinion but if you guys prefer sticking with the `os` library feel free to ignore this, I can edit the MR to use os.sep of course.

**Comment by robin-maillot** [comment]
@FateScript I'm having issues to sign the cla, I have signed it several times and it seems to be okay but it still won't validate in the workflow.

Also please let me know if proposing a simpler os.sep version would help get this merged quicker, I would love to be able to use your repo on windows.

- Robin

**Comment by FateScript** [comment]
@robin-maillot a simple os.sep version could help this PR merged quicker.

**Comment by robin-maillot** [comment]
> @robin-maillot a simple os.sep version could help this PR merged quicker. Did you sign in with your github account?

Hi @FateScript, I gave it one last shot with (hopefully fixing the workflow), if you can try rerunning the workflow one last time that would be great. If it does not work I will revert the changes and go for a simpler fix no problem.

Have a good day.

**Comment by FateScript** [comment]
I still could not find your name on [cla-assistant](https://cla-assistant.io) @robin-maillot

**Comment by robin-maillot** [comment]
> I still could not find your name on [cla-assistant](https://cla-assistant.io) @robin-maillot

I tried with a different browser with cookies enables, could you check again, now when I click on the cla link I get the following message:

image

**Comment by FateScript** [comment]
I find your name now @robin-maillot , but it's wired that the workflow could not find you.

**Comment by robin-maillot** [comment]
> I find your name now @robin-maillot , but it's wired that the workflow could not find you. Some PR after you(such as the latest one) could get the info correctly.

@FateScript sorry it was my first time using the CLA it turns out that I had set my email address wrong in the local config and it was expecting my other account to sign the CLA (which I now did). I hope this works and sorry for the inconvenience.

**Comment by FateScript** [comment]
Thanks for contributing @robinmaillot , could you please upload a simple os.sep version.

**Comment by robin-maillot** [comment]
> Thanks for contributing @robinmaillot , could you please upload a simple os.sep version.

@FateScript  I provided a new MR as requested here: https://github.com/Megvii-BaseDetection/YOLOX/pull/1100

**Pull request closed without merging**
