### PR TITLE
Adding W&B Logger

### PR DESCRIPTION
**Pull request by digantamisra98**
This PR adds support for [W&B](https://wandb.ai/site) logging, currently experimental and WIP.

### CODE REVIEW

**Comment by hoangkhoiLE** [comment]
@digantamisra98  Hello,

Thank for your work. I try to follow your version and got this bug.
image
Can you tell me how to fix it ?

Best regard !

**Comment by digantamisra98** [comment]
@hoangkhoiLE Looking into this, should be an easy fix. Thanks for pointing it out.

**Comment by hoangkhoiLE** [comment]
@digantamisra98  Hope you will fix it soon !

**Comment by digantamisra98** [comment]
@hoangkhoiLE Did you have wandb enabled by passing either `--wandb` or `-wb` flag in the training CLI script?

**Comment by qingswu** [comment]
> 
> 
> image Hello I try your version fixed and got this bug. Can you tell me how to fix it ? Thank in advance !
> 
> Best regard !!

a different topic: what kind of tool are you using to display the annotations of python objects shown in your picture? Thank you!

**Comment by hoangkhoiLE** [comment]
> > image Hello I try your version fixed and got this bug. Can you tell me how to fix it ? Thank in advance !
> > Best regard !!
> 
> a different topic: what kind of tool are you using to display the annotations of python objects shown in your picture? Thank you!

I use Snipping tool :D

**Comment by hoangkhoiLE** [comment]
image

Hello @digantamisra98 ,

I got a problem when i try to precise my output_dir at file "yolox_s.py" with my directory of my drive. But it caused this error. Can you show me the way to have a good output_dir for saving checkpoint. Thank in advance

**Comment by hoangkhoiLE** [comment]
Hello,

I try your version actual, and got this error. 
image
It's a problem about my output_dir is not good, which i set it here:
image
my command to train is:
```
!python ./tools/train.py -f yolox_s.py -d 1 -b 16  -o   --cache  --wandb
```
Please help me to understand how can i fix that ! Thank you in advance !!

**Comment by Dolpheyn** [comment]
Waiting for this to get merged before I start training for my final year university project. Go @digantamisra98 you can do it!!

**Comment by hoangkhoiLE** [comment]
Dear @digantamisra98,
I take a look at your work. It seems like you just run 1 epoch each time, the problem I faced is at the moment we need to update our latest_ckpt at saving directory. I think that you can run 2, 3 times to face a problem. Thank in advance !

**Comment by hoangkhoiLE** [comment]
Dear @digantamisra98 , you can take "mini-coco" with about 100 image here ! https://drive.google.com/file/d/16N3u36ycNd70m23IM7vMuRQXejAJY9Fs/view

**Comment by digantamisra98** [comment]
@hoangkhoiLE Got it, thanks, working on it.

**Comment by digantamisra98** [comment]
@AyushExel are you working on this branch?

**Comment by AyushExel** [comment]
@digantamisra98 no not on this branch currently. I'll make a separate PR.

**Comment by digantamisra98** [comment]
@AyushExel do you want me to thus close this PR?

**Comment by AyushExel** [comment]
Sure

**Pull request closed without merging**
