### PR TITLE
in memory of Dr. Jian Sun

### PR DESCRIPTION
**Pull request by FateScript**
PTAL @GOATmessi7  @Joker316701882  @zengarden

### CODE REVIEW

**Comment by GOATmessi7** [comment]
R. I. P 
我也不知道再说些什么，脑子里还是很空，很迷茫

**Comment by zengarden** [comment]
R.I.P.!

**Comment by Joker316701882** [comment]
In memory of Dr. Jian Sun. R.I.P.!

**Comment by skpawar1305** [comment]
R.I.P.

**Pull request merged**
