### PR TITLE
Add custom training sample code and dataset

### PR DESCRIPTION
**Pull request by SWHL**
- add a `exps/custom` directory to quickly start training your own data set.
- update `docs/train_custom_data.md`.
- add `mini-coco128`(18M) sample data set in coco format, which is convenient for downloading and testing the native training environment. (The link in the `docs/train_custom_data.md`)

### CODE REVIEW

**Review by ruinmessi — COMMENTED** [review]
Thx for your contribution! Could you change the exps/custom to exps/example/custom?

**Comment by SWHL** [comment]
> Thx for your contribution! Could you change the exps/custom to exps/example/custom?

Of course

**Review by ruinmessi — COMMENTED** [review]
LGTM.

**Comment by SWHL** [comment]
#### fix(evaluator): fix n_samples=0 bug for the len of dataloader is 1
---
When the length of the val dataloader is 1, the `n_samples=0`:
https://github.com/Megvii-BaseDetection/YOLOX/blob/3640b242bdd752715ea6e38dfb7ad7c2fbe9adf4/yolox/evaluators/coco_evaluator.py#L86

And this will meet the following error:
<details>
<summary>Click to expand</summary>

```python
File "tools/train.py", line 115, in <module>
    dist_url=dist_url, args=(exp, args)
             │               │    └ Namespace(batch_size=16, ckpt=None, devices=1, dist_backend='nccl', dist_url=None, exp_file='exps/default/nano_custom.py', ex...
             │               └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...
             └ 'auto'

> File "/data/SWHL/YOLOX-main/yolox/core/launch.py", line 68, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x2b3bf3373d08>

  File "tools/train.py", line 101, in main
    trainer.train()
    │       └ <function Trainer.train at 0x2b3bf1899730>
    └ <yolox.core.trainer.Trainer object at 0x2b3bf3381198>

  File "/data/SWHL/YOLOX-main/yolox/core/trainer.py", line 58, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x2b3bf18996a8>
    └ <yolox.core.trainer.Trainer object at 0x2b3bf3381198>

  File "/data/SWHL/YOLOX-main/yolox/core/trainer.py", line 68, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x2b3bf3292b70>
    └ <yolox.core.trainer.Trainer object at 0x2b3bf3381198>

  File "/data/SWHL/YOLOX-main/yolox/core/trainer.py", line 200, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x2b3bf3292e18>
    └ <yolox.core.trainer.Trainer object at 0x2b3bf3381198>

  File "/data/SWHL/YOLOX-main/yolox/core/trainer.py", line 284, in evaluate_and_save_model
    self.is_distributed)
    │    └ False
    └ <yolox.core.trainer.Trainer object at 0x2b3bf3381198>

  File "/data/SWHL/YOLOX-main/yolox/exp/yolox_base.py", line 257, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN(
           │         │              (backbone): CSPDarknet(
           │         │                (stem): Focus(
           │         │                  (conv): BaseConv(
           │         │                    (conv): ...
           │         └ <function CustomEvaluator.evaluate at 0x2b3bf327bc80>
           └ <yolox.evaluators.custom_evaluator.CustomEvaluator object at 0x2b3bae5f5ac8>

  File "/data/SWHL/YOLOX-main/yolox/evaluators/coco_evaluator.py", line 130, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([0., 0., 0.], device='cuda:0')
                   │    │                   └ []
                   │    └ <function CustomEvaluator.evaluate_prediction at 0x2b3bf327bd90>
                   └ <yolox.evaluators.custom_evaluator.CustomEvaluator object at 0x2b3bae5f5ac8>

 File "/data/SWHL/YOLOX-main/yolox/evaluators/coco_evaluator.py", line 178, in evaluate_prediction
    a_infer_time = 1000 * inference_time / (n_samples * self.dataloader.batch_size)
                          │                 │           │    │          └ 16
                          │                 │           │    └ <torch.utils.data.dataloader.DataLoader object at 0x2b3b82927a58>
                          │                 │           └ <yolox.evaluators.custom_evaluator.CustomEvaluator object at 0x2b3bae5f5ac8>
                          │                 └ 0.0
                          └ 0.0

ZeroDivisionError: float division by zero
```
</details>

**Comment by ruinmessi** [comment]
Thx, could you change it to :
```python
n_samples = max(len(self.dataloader) - 1, 1)
```
which I think would be better.

**Comment by SWHL** [comment]
> Thx, could you change it to :
> 
> ```python
> n_samples = max(len(self.dataloader) - 1, 1)
> ```
> 
> which I think would be better.

Of course , it is indeed better to implement this way.

**Pull request merged**
