### PR TITLE
feat: add option for decode output in export_onnx.py

### PR DESCRIPTION
**Pull request by wep21**

### CODE REVIEW

**Comment by wep21** [comment]
@FateScript Could you review this?

**Comment by FateScript** [comment]
Thx for contribution. Could you plz tell us why it's needed?

**Comment by FateScript** [comment]
@wep21 Did you try export nms and run it suceessfully(with the correct output)?

**Comment by wep21** [comment]
@FateScript Yes, I have tested it with my ros2 implementation. https://github.com/tier4/tensorrt_yolox
Is it preferable to share some python codes to reproduce this?

**Comment by FateScript** [comment]
> @FateScript Yes, I have tested it with my ros2 implementation. https://github.com/tier4/tensorrt_yolox Is it preferable to share some python codes to reproduce this?

Thx, I could have a try myself.

**Comment by wep21** [comment]
@jbohnslav Yes, I created a conversion script with onnx graph surgeon.
https://github.com/wep21/yolox_onnx_modifier

**Pull request merged**
