### PR TITLE
Update yolox.cpp: fix INPUT_BLOB_NAME & OUTPUT_BLOB_NAME

### PR DESCRIPTION
**Pull request by michelpromonet**
Hi,

This merge request update the name of input & output blob name.
It allow to run tensorrt onnx models converted using `trtexec --onnx=yolox_s.onnx --saveEngine=yolox_s.trt`

Best Regards,
Michel.

### CODE REVIEW

**Comment by FateScript** [comment]
LGTM.

**Comment by starlipernl** [comment]
This change does not work with torch2trt converted models.

**Comment by michelpromonet** [comment]
Hi @starlipernl 

I was not able to install trt2torch, in order to convert the model, I used :
``` trtexec --onnx=yolox_s.onnx --fp16 --saveEngine=yolox_s.trt```

Best Regards,
Michel.

**Comment by starlipernl** [comment]
I used the latest release of both YOLOX and torch2trt with Tensorrt version 8.6.1. When trying to run the converted model with the cpp demo script I got the following error: 
Cannot find binding of given name: images.

This is because torch2trt defaults to input_0 and output_0 for the binding names. There may be a way to specific the input and output name bindings during torch2trt conversion within the trt.py file in this repo I just did not dig too much into it.

**Comment by FateScript** [comment]
I have already reverted this pr in #1792.  
@michelpromonet Your contribution is saved in README now.

**Pull request merged**
