### PR TITLE
upgrade onnxsim to v0.4.1

### PR DESCRIPTION
**Pull request by daquexian**
I'm the author of onnx-simplifier. Recently I published onnxsim v0.4.1. In the latest version, dynamic input shapes are natively supported with no need for extra flags like `dynamic_input_shapes` and `input_shapes`.

### CODE REVIEW

**Comment by FateScript** [comment]
Thanks for your contribution @daquexian , Plz lint your code to pass the workflow.
BTW, have your ever double checked exported onnx model ?

**Comment by daquexian** [comment]
@FateScript Fixed.

I haven't checked the exported model because I'm not familiar with the usage. Could you please help check it if there is some concern?

**Comment by FateScript** [comment]
> @FateScript Fixed.
> 
> Could you please help check it if there is some concern?

Ok,  I will check this later. Plz remind me if this PR is not merged for a week. Thanks.

**Comment by daquexian** [comment]
> > @FateScript Fixed.
> > Could you please help check it if there is some concern?
> 
> Ok, I will check this later. Plz remind me if this PR is not merged for a week. Thanks.

All right. Thanks!

**Comment by tadejsv** [comment]
@FateScript what is the status of this PR?

**Comment by FateScript** [comment]
> @FateScript what is the status of this PR?

I have check the onnx generated by this pr and it works. I will merge this PR ASAP.

**Comment by FateScript** [comment]
LGTM. Thanks for your contribution @daquexian .

**Pull request merged**
